name: awsearth
channels:
  - conda-forge
  - informaticslab
dependencies:
  - python=3.6

  - boto3
  - dask
  - dask-kubernetes
  - distributed
  - ipywidgets
  - ipyleaflet
  - iris
  - jupyterlab
  - numpy
  - matplotlib
  - mo_aws_earth
  - pandas
  - scipy
